### ISSUE TITLE
fix GitHub workflow warning

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#10]
https://github.com/philj56/gbcc-android/actions/runs/3337454331

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

**Comment by philj56** [comment]
:+1: Cheers, I've updated the workflow.
