### ISSUE TITLE
fix screenshot bottom color

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#11]
![Screenshot_20221028-111245_Trebuchet](https://user-images.githubusercontent.com/109885044/198497929-28bdd1de-0e97-4700-ad7f-75d4079fbb6c.png)

**Comment by philj56** [comment]
Yeah this is something that annoys me as well, the bottom curves get moved when the nav bar is shown. For me though, the screenshot gets taken before this move happens. I'll have a look and see if there's anything straightforward I can do.

**Comment by soundsnow** [comment]
![Screenshot_20221029-093821_Trebuchet](https://user-images.githubusercontent.com/109885044/198756852-9b1e3de5-50a6-4c8b-ad5d-1df0f1d69e52.png)
![Screenshot_20221029-093839_Trebuchet](https://user-images.githubusercontent.com/109885044/198756869-2bcab4c8-6945-45ad-b331-e8424eb13502.png)

**Comment by philj56** [comment]
Ok, this should be fixed in ba84319cc0ad5a24ac7d941645a75274dc8807da.
