### ISSUE TITLE
gbc emulator options

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#13]
"gameboy_model",
      "System - Emulated Model (Requires Restart)",
      "Emulated Model (Requires Restart)",
      "Chooses which system model the content should be started on. Certain games may activate special in-game features when ran on specific models. This option requires a content restart in order to take effect.",
      NULL,
      "system",
      {
         { "Auto",                 "Auto Detect DMG/CGB"                       },
         { "Auto (SGB)",           "Auto Detect DMG/SGB/CGB"                   },
         { "Game Boy",             "Game Boy (DMG-CPU B)"                      },
         { "Game Boy Color C",     "Game Boy Color (CPU-CGB C) (Experimental)" },
         { "Game Boy Color",       "Game Boy Color (CPU-CGB E)"                },
         { "Game Boy Advance",     NULL },
         { "Super Game Boy",       "Super Game Boy NTSC"                       },
         { "Super Game Boy PAL",   NULL },
         { "Super Game Boy 2",     NULL },
         { NULL, NULL },
      },
      "Auto"
   },
   
      "gameboy_auto_sgb_model",
      "System - Auto Detected SGB Model (Requires Restart)",
      "Auto Detected SGB Model (Requires Restart)",
      "Specifies which model of Super Game Boy hardware to emulate when SGB content is automatically detected. This option requires a content restart in order to take effect.",
      NULL,
      "system",
      {
         { "Super Game Boy",       "Super Game Boy NTSC" },
         { "Super Game Boy PAL",   NULL },
         { "Super Game Boy 2",     NULL },
         { NULL, NULL },
      },
      "Super Game Boy"
   },
   
      "gameboy_rtc",
      "System - Real Time Clock Emulation",
      "Real Time Clock Emulation",
      "Specifies how the emulation of the real-time clock feature used in certain Game Boy and Game Boy Color games should function.",
      NULL,
      "system",
      {
         { "sync to system clock", "Sync to System Clock" },
         { "accurate",             "Accurate"             },
         { NULL, NULL },
      },
      "sync to system clock"
   },
   
      "gameboy_mono_palette",
      "Video - GB Mono Palette",
      "GB Mono Palette",
      "Selects the color palette that should be used when playing Game Boy games.",
      NULL,
      "video",
      {
         { "greyscale", "Greyscale"               },
         { "lime",      "Lime (Game Boy)"         },
         { "olive",     "Olive (Game Boy Pocket)" },
         { "teal",      "Teal (Game Boy Light)"   },
         { NULL, NULL },
      },
      "greyscale"
   },
   
      "gameboy_color_correction_mode",
      "Video - GBC Color Correction",
      "GBC Color Correction",
      "Defines which type of color correction should be applied when playing Game Boy Color games.",
      NULL,
      "video",
      {
         { "emulate hardware",    "Modern – Balanced"            },
         { "accurate",            "Modern – Accurate"            },
         { "preserve brightness", "Modern – Boost Contrast"      },
         { "reduce contrast",     "Reduce Contrast"              },
         { "correct curves",      "Correct Color Curves"         },
         { "harsh reality",       "Harsh Reality (Low Contrast)" },
         { "off",                 "Disabled"                     },
         { NULL, NULL },
      },
      "emulate hardware"
   },
   
      "gameboy_light_temperature",
      "Video - Ambient Light Temperature",
      "Ambient Light Temperature",
      "Simulates an ambient light's effect on non-backlit Game Boy screens, by setting a user-controlled color temperature. This option has no effect if the content is run on an original Game Boy (DMG) emulated model.",
      NULL,
      "video",
      {
         { "1.0",   "1000K (Warmest)"       },
         { "0.9",   "1550K" },
         { "0.8",   "2100K" },
         { "0.7",   "2650K" },
         { "0.6",   "3200K" },
         { "0.5",   "3750K" },
         { "0.4",   "4300K" },
         { "0.3",   "4850K" },
         { "0.2",   "5400K" },
         { "0.1",   "5950K" },
         { "0",     "6500K (Neutral White)" },
         { "-0.1",  "7050K" },
         { "-0.2",  "7600K" },
         { "-0.3",  "8150K" },
         { "-0.4",  "8700K" },
         { "-0.5",  "9250K" },
         { "-0.6",  "9800K" },
         { "-0.7", "10350K" },
         { "-0.8", "10900K" },
         { "-0.9", "11450K" },
         { "-1.0", "12000K (Coolest)"       },
         { NULL, NULL },
      },
      "0"
   },
   
      "gameboy_border",
      "Video - Display Border",
      "Display Border",
      "Defines when to display an on-screen border around the content.",
      NULL,
      "video",
      {
         { "always",              "Always"                  },
         { "Super Game Boy only", "Only for Super Game Boy" },
         { "never",               "Disabled"                },
         { NULL, NULL },
      },
      "Super Game Boy only"
   },
   
      "gameboy_high_pass_filter_mode",
      "Audio - Highpass Filter",
      "Highpass Filter",
      "Applies a filter to the audio output, removing certain pop sounds caused by the DC Offset. If disabled, the sound will be rendered as output by the Game Boy APU, but popping effects will be heard when the emulator is paused or resumed. 'Accurate' will apply a global filter, masking popping sounds while also reducing lower frequencies. 'Preserve Waveform' applies the filter only to the DC Offset.",
      NULL,
      "audio",
      {
         { "accurate",         "Accurate"              },
         { "remove dc offset", "Preserve Waveform"     },
         { "off",              "Disabled"              },
         { NULL, NULL },
      },
      "accurate"
   },
   
      "gameboy_audio_interference",
      "Audio - Interference Volume",
      "Interference Volume",
      "Controls the volume of the buzzing effect caused by the electrical interference between the Game Boy SoC and the system speakers.",
      NULL,
      "audio",
      {
         { "0",   "0%"   },
         { "5",   "5%"   },
         { "10",  "10%"  },
         { "15",  "15%"  },
         { "20",  "20%"  },
         { "25",  "25%"  },
         { "30",  "30%"  },
         { "35",  "35%"  },
         { "40",  "40%"  },
         { "45",  "45%"  },
         { "50",  "50%"  },
         { "55",  "55%"  },
         { "60",  "60%"  },
         { "65",  "65%"  },
         { "70",  "70%"  },
         { "75",  "75%"  },
         { "80",  "80%"  },
         { "85",  "85%"  },
         { "90",  "90%"  },
         { "95",  "95%"  },
         { "100", "100%" },
         { NULL, NULL },
      },
      "0"
   },
   
      "gameboy_rumble",
      "Input - Rumble Mode",
      "Rumble Mode",
      "Defines which type of content should trigger rumble effects.",
      NULL,
      "input",
      {
         { "all games",            "Always"                        },
         { "rumble-enabled games", "Only for rumble-enabled games" },
         { "never",                "Never"                      },
         { NULL, NULL },
      },
      "rumble-enabled games"
   },

   /* Core options used in dual cart mode */

   {
      "gameboy_link",
      "System - Link Cable Emulation",
      "Link Cable Emulation",
      "Enables the emulation of the link cable, allowing communication and exchange of data between two Game Boy systems.",
      NULL,
      "system",
      {
         { "enabled",  "Enabled" },
         { "disabled", "Disabled" },
         { NULL, NULL },
      },
      "enabled"
   },
   
      "gameboy_screen_layout",
      "System - Screen Layout",
      "Screen Layout",
      "When emulating two systems at once, this option defines the respective position of the two screens.",
      NULL,
      "system",
      {
         { "top-down",   "Top-Down"   },
         { "left-right", "Left-Right" },
         { NULL, NULL },
      },
      "top-down"
   },
   
      "gameboy_audio_output",
      "System - Audio Output",
      "Audio Output",
      "Selects which of the two emulated Game Boy systems should output audio.",
      NULL,
      "system",
      {
         { "Game Boy #1", NULL },
         { "Game Boy #2", NULL },
         { NULL, NULL },
      },
      "Game Boy #1"
   },
   
      "gameboy_model_1",
      "System - Emulated Model for Game Boy #1 (Requires Restart)",
      "Emulated Model for Game Boy #1 (Requires Restart)",
      "Chooses which system model the content should be started on for Game Boy #1. Certain games may activate special in-game features when ran on specific models. This option requires a content restart in order to take effect.",
      NULL,
      "system",
      {
         { "Auto",                 "Auto Detect DMG/CGB"                       },
         { "Auto (SGB)",           "Auto Detect DMG/SGB/CGB"                   },
         { "Game Boy",             "Game Boy (DMG-CPU B)"                      },
         { "Game Boy Color C",     "Game Boy Color (CPU-CGB C) (Experimental)" },
         { "Game Boy Color",       "Game Boy Color (CPU-CGB E)"                },
         { "Game Boy Advance",     NULL },
         { "Super Game Boy",       "Super Game Boy NTSC"                       },
         { "Super Game Boy PAL",   NULL },
         { "Super Game Boy 2",     NULL },
         { NULL, NULL },
      },
      "Auto"
   },
   
      "gameboy_auto_sgb_model_1",
      "System - Auto Detected SGB Model for Game Boy #1 (Requires Restart)",
      "Auto Detected SGB Model for Game Boy #1 (Requires Restart)",
      "Specifies which model of Super Game Boy hardware to emulate when SGB content is automatically detected for Game Boy #1. This option requires a content restart in order to take effect.",
      NULL,
      "system",
      {
         { "Super Game Boy",       "Super Game Boy NTSC" },
         { "Super Game Boy PAL",   NULL },
         { "Super Game Boy 2",     NULL },
         { NULL, NULL },
      },
      "Super Game Boy"
   },
   
      "gameboy_model_2",
      "System - Emulated Model for Game Boy #2 (Requires Restart)",
      "Emulated Model for Game Boy #2 (Requires Restart)",
      "Chooses which system model the content should be started on for Game Boy #2. Certain games may activate special in-game features when ran on specific models. This option requires a content restart in order to take effect.",
      NULL,
      "system",
      {
         { "Auto",                 "Auto Detect DMG/CGB"                       },
         { "Auto (SGB)",           "Auto Detect DMG/SGB/CGB"                   },
         { "Game Boy",             "Game Boy (DMG-CPU B)"                      },
         { "Game Boy Color C",     "Game Boy Color (CPU-CGB C) (Experimental)" },
         { "Game Boy Color",       "Game Boy Color (CPU-CGB E)"                },
         { "Game Boy Advance",     NULL },
         { "Super Game Boy",       "Super Game Boy NTSC"                       },
         { "Super Game Boy PAL",   NULL },
         { "Super Game Boy 2",     NULL },
         { NULL, NULL },
      },
      "Auto"
   },
   
      "gameboy_auto_sgb_model_2",
      "System - Auto Detected SGB Model for Game Boy #2 (Requires Restart)",
      "Auto Detected SGB Model for Game Boy #2 (Requires Restart)",
      "Specifies which model of Super Game Boy hardware to emulate when SGB content is automatically detected for Game Boy #2. This option requires a content restart in order to take effect.",
      NULL,
      "system",
      {
         { "Super Game Boy",       "Super Game Boy NTSC" },
         { "Super Game Boy PAL",   NULL },
         { "Super Game Boy 2",     NULL },
         { NULL, NULL },
      },
      "Super Game Boy"
   },
   
      "gameboy_mono_palette_1",
      "Video - GB Mono Palette for Game Boy #1",
      "GB Mono Palette for Game Boy #1",
      "Selects the color palette that should be used when playing Game Boy games on Game Boy #1.",
      NULL,
      "video",
      {
         { "greyscale", "Greyscale"               },
         { "lime",      "Lime (Game Boy)"         },
         { "olive",     "Olive (Game Boy Pocket)" },
         { "teal",      "Teal (Game Boy Light)"   },
         { NULL, NULL },
      },
      "greyscale"
   },
   
      "gameboy_mono_palette_2",
      "Video - GB Mono Palette for Game Boy #2",
      "GB Mono Palette for Game Boy #2",
      "Selects the color palette that should be used when playing Game Boy games on Game Boy #2.",
      NULL,
      "video",
      {
         { "greyscale", "Greyscale"               },
         { "lime",      "Lime (Game Boy)"         },
         { "olive",     "Olive (Game Boy Pocket)" },
         { "teal",      "Teal (Game Boy Light)"   },
         { NULL, NULL },
      },
      "greyscale"
   },
   
      "gameboy_color_correction_mode_1",
      "Video - GBC Color Correction for Game Boy #1",
      "GBC Color Correction for Game Boy #1",
      "Defines which type of color correction should be applied when playing Game Boy Color games on Game Boy #1.",
      NULL,
      "video",
      {
         { "emulate hardware",    "Modern – Balanced"            },
         { "accurate",            "Modern – Accurate"            },
         { "preserve brightness", "Modern – Boost Contrast"      },
         { "reduce contrast",     "Reduce Contrast"              },
         { "correct curves",      "Correct Color Curves"         },
         { "harsh reality",       "Harsh Reality (Low Contrast)" },
         { "off",                 "Disabled"                     },
         { NULL, NULL },
      },
      "emulate hardware"
   },
   
      "gameboy_color_correction_mode_2",
      "Video - GBC Color Correction for Game Boy #2",
      "GBC Color Correction for Game Boy #2",
      "Defines which type of color correction should be applied when playing Game Boy Color games on Game Boy #2.",
      NULL,
      "video",
      {
         { "emulate hardware",    "Modern – Balanced"            },
         { "accurate",            "Modern – Accurate"            },
         { "preserve brightness", "Modern – Boost Contrast"      },
         { "reduce contrast",     "Reduce Contrast"              },
         { "correct curves",      "Correct Color Curves"         },
         { "harsh reality",       "Harsh Reality (Low Contrast)" },
         { "off",                 "Disabled"                     },
         { NULL, NULL },
      },
      "emulate hardware"
   },
   
      "gameboy_light_temperature_1",
      "Video - Ambient Light Temperature for Game Boy #1",
      "Ambient Light Temperature for Game Boy #1",
      "Simulates an ambient light's effect on non-backlit Game Boy screens, by setting a user-controlled color temperature applied to the screen of Game Boy #1. This option has no effect if the content is run on an original Game Boy (DMG) emulated model.",
      NULL,
      "video",
      {
         { "1.0",   "1000K (Warmest)"       },
         { "0.9",   "1550K" },
         { "0.8",   "2100K" },
         { "0.7",   "2650K" },
         { "0.6",   "3200K" },
         { "0.5",   "3750K" },
         { "0.4",   "4300K" },
         { "0.3",   "4850K" },
         { "0.2",   "5400K" },
         { "0.1",   "5950K" },
         { "0",     "6500K (Neutral White)" },
         { "-0.1",  "7050K" },
         { "-0.2",  "7600K" },
         { "-0.3",  "8150K" },
         { "-0.4",  "8700K" },
         { "-0.5",  "9250K" },
         { "-0.6",  "9800K" },
         { "-0.7", "10350K" },
         { "-0.8", "10900K" },
         { "-0.9", "11450K" },
         { "-1.0", "12000K (Coolest)"       },
         { NULL, NULL },
      },
      "0"
   },
   
      "gameboy_light_temperature_2",
      "Video - Ambient Light Temperature for Game Boy #2",
      "Ambient Light Temperature for Game Boy #2",
      "Simulates an ambient light's effect on non-backlit Game Boy screens, by setting a user-controlled color temperature applied to the screen of Game Boy #2. This option has no effect if the content is run on an original Game Boy (DMG) emulated model.",
      NULL,
      "video",
      {
         { "1.0",   "1000K (Warmest)"       },
         { "0.9",   "1550K" },
         { "0.8",   "2100K" },
         { "0.7",   "2650K" },
         { "0.6",   "3200K" },
         { "0.5",   "3750K" },
         { "0.4",   "4300K" },
         { "0.3",   "4850K" },
         { "0.2",   "5400K" },
         { "0.1",   "5950K" },
         { "0",     "6500K (Neutral White)" },
         { "-0.1",  "7050K" },
         { "-0.2",  "7600K" },
         { "-0.3",  "8150K" },
         { "-0.4",  "8700K" },
         { "-0.5",  "9250K" },
         { "-0.6",  "9800K" },
         { "-0.7", "10350K" },
         { "-0.8", "10900K" },
         { "-0.9", "11450K" },
         { "-1.0", "12000K (Coolest)"       },
         { NULL, NULL },
      },
      "0"
   },
   
      "gameboy_high_pass_filter_mode_1",
      "Audio - Highpass Filter for Game Boy #1",
      "Highpass Filter for Game Boy #1",
      "Applies a filter to the audio output for Game Boy #1, removing certain pop sounds caused by the DC Offset. If disabled, the sound will be rendered as output by the Game Boy APU, but popping effects will be heard when the emulator is paused or resumed. 'Accurate' will apply a global filter, masking popping sounds while also reducing lower frequencies. 'Preserve Waveform' applies the filter only to the DC Offset.",
      NULL,
      "audio",
      {
         { "accurate",         "Accurate"              },
         { "remove dc offset", "Preserve Waveform"     },
         { "off",              "disabled"              },
         { NULL, NULL },
      },
      "accurate"
   },
   
      "gameboy_high_pass_filter_mode_2",
      "Audio - Highpass Filter for Game Boy #2",
      "Highpass Filter for Game Boy #2",
      "Applies a filter to the audio output for Game Boy #2, removing certain pop sounds caused by the DC Offset. If disabled, the sound will be rendered as output by the Game Boy APU, but popping effects will be heard when the emulator is paused or resumed. 'Accurate' will apply a global filter, masking popping sounds while also reducing lower frequencies. 'Preserve Waveform' applies the filter only to the DC Offset.",
      NULL,
      "audio",
      {
         { "accurate",         "Accurate"              },
         { "remove dc offset", "Preserve Waveform"     },
         { "off",              "disabled"              },
         { NULL, NULL },
      },
      "accurate"
   },
   
      "gameboy_audio_interference_1",
      "Audio - Interference Volume for Game Boy #1",
      "Interference Volume for Game Boy #1",
      "Controls the volume of the buzzing effect caused by the electrical interference between the Game Boy SoC and the system speakers on Game Boy #1.",
      NULL,
      "audio",
      {
         { "0",   "0%"   },
         { "5",   "5%"   },
         { "10",  "10%"  },
         { "15",  "15%"  },
         { "20",  "20%"  },
         { "25",  "25%"  },
         { "30",  "30%"  },
         { "35",  "35%"  },
         { "40",  "40%"  },
         { "45",  "45%"  },
         { "50",  "50%"  },
         { "55",  "55%"  },
         { "60",  "60%"  },
         { "65",  "65%"  },
         { "70",  "70%"  },
         { "75",  "75%"  },
         { "80",  "80%"  },
         { "85",  "85%"  },
         { "90",  "90%"  },
         { "95",  "95%"  },
         { "100", "100%" },
         { NULL, NULL },
      },
      "0"
   },
   
      "gameboy_audio_interference_2",
      "Audio - Interference Volume for Game Boy #2",
      "Interference Volume for Game Boy #2",
      "Controls the volume of the buzzing effect caused by the electrical interference between the Game Boy SoC and the system speakers on Game Boy #2.",
      NULL,
      "audio",
      {
         { "0",   "0%"   },
         { "5",   "5%"   },
         { "10",  "10%"  },
         { "15",  "15%"  },
         { "20",  "20%"  },
         { "25",  "25%"  },
         { "30",  "30%"  },
         { "35",  "35%"  },
         { "40",  "40%"  },
         { "45",  "45%"  },
         { "50",  "50%"  },
         { "55",  "55%"  },
         { "60",  "60%"  },
         { "65",  "65%"  },
         { "70",  "70%"  },
         { "75",  "75%"  },
         { "80",  "80%"  },
         { "85",  "85%"  },
         { "90",  "90%"  },
         { "95",  "95%"  },
         { "100", "100%" },
         { NULL, NULL },
      },
      "0"
   },
   
      "gameboy_rumble_1",
      "Input - Rumble Mode for Game Boy #1",
      "Rumble Mode for Game Boy #1",
      "Defines which type of content should trigger rumble effects when played on Game Boy #1.",
      NULL,
      "input",
      {
         { "all games",            "Always"                        },
         { "rumble-enabled games", "Only for rumble-enabled games" },
         { "never",                "Never"                         },
         { NULL, NULL },
      },
      "rumble-enabled games"
   },
   
      "gameboy_rumble_2",
      "Input - Rumble Mode for Game Boy #2",
      "Rumble Mode for Game Boy #2",
      "Defines which type of content should trigger rumble effects when played on Game Boy #2.",
      NULL,
      "input",
      {
         { "all games",            "Always"                        },
         { "rumble-enabled games", "Only for rumble-enabled games" },
         { "never",                "Never"                         },
         { NULL, NULL },
      },
      "rumble-enabled games"
   },

**Comment by soundsnow** [comment]
@philj56

**Comment by philj56** [comment]
Thanks, but a big list of features from another emulator isn't particularly useful. Some of these features are already in GBCC, some are planned, and some aren't relevant.
