### ISSUE TITLE
Remapping Physical Keys

### ISSUE THREAD

**Issue by CatWithCode** [philj56/gbcc-android#14]
I have a Unihertz Titan witch has a Physical keyboard on it. I want to use the Keys of it to control the games. Other emulators allow you to choose a Button (Like A, B or Start) and map any keys/button/input (external gamepad/connected Keyboard and so on) to it. Is this possible in gbcc too?

**Comment by philj56** [comment]
Not at the moment unfortunately. I just have gamepad remapping:

![remap](https://user-images.githubusercontent.com/13610623/198735860-4a1296e8-0c06-493f-ae8f-173ea907d362.png)

This was on my to-do list before I took a break from gbcc though. I'm trying to get back into development of it at the moment, so I'll take a look over the weekend and let you know. The main problem is one of UI I think.

**Comment by CatWithCode** [comment]
omg! GREAT JOB!!!

**Comment by CatWithCode** [comment]
![grafik](https://user-images.githubusercontent.com/56090976/199558666-f70b0d15-b715-4c29-8a5d-7282cc847756.png)

**Comment by philj56** [comment]
:+1: happy to help!
