### ISSUE TITLE
Exporting images to a gallery or real printer

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#15]
screenshots
storage/emulated/0/Pictures/Super Mario Land 2 - 6 Golden Coins (USA, Europe) (Rev 2)_20221029-092846.png
real printer for Game Boy Camera

**Comment by philj56** [comment]
Camera picture export is on the [todo list](https://github.com/philj56/gbcc-android/issues/1). I also have a fun idea for printer stuff as well, but it'll probably be a while until I get round to it.

**Comment by soundsnow** [comment]
![SameBoy](https://user-images.githubusercontent.com/109885044/200097872-ee79e9b4-5106-4e99-b59f-08927e5730ca.jpg)

**Comment by soundsnow** [comment]
![SameBoy](https://user-images.githubusercontent.com/109885044/200097872-ee79e9b4-5106-4e99-b59f-08927e5730ca.jpg)

**Comment by philj56** [comment]
Ok, I've added printer support in 036dc078661fa1942ad69e59b0987341dfeb9b12:

![zopfli_printer](https://user-images.githubusercontent.com/13610623/201325915-47a1f916-d3b6-4898-afb8-fa14a4451a2d.png)

You can save the printouts to your phone's storage as well, which means this is also a way to export camera images.

**Comment by krvkz** [comment]
@philj56 sorry, I don't like bringing closed threads back up, but I for the life of me can't figure out how to export the photos to my local storage. I also haven't been able to find an explanation in the documentation. Would you be willing to shed some light on this for me, please?

**Comment by philj56** [comment]
Have you installed it from the play store, or the debug apk from github? The version on the play store doesn't have the printer in it yet (I'll try and do a proper release soon).

If you're on the latest build from here, you need to print your camera image, then the save button in the top right of the above screenshot should do what you want.

**Comment by krvkz** [comment]
Ah! I was just using the version in the Play Store. I just downloaded the debug apk, and it's working perfectly! I will continue testing the debug apk from now on. Thank you, and I am seriously loving this emulator BTW. Keep up the great work!
