### ISSUE TITLE
warp and box arts

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#16]
![Screenshot_20221029-093333_Trebuchet](https://user-images.githubusercontent.com/109885044/198755852-8808d44d-a4eb-417f-85d5-682de72f4cb1.png)
![Screenshot_20221029-093249_Trebuchet](https://user-images.githubusercontent.com/109885044/198755854-c88b8b1c-6164-4fd0-a250-4be5e8365e06.png)

**Comment by soundsnow** [comment]
box arts
![image148](https://user-images.githubusercontent.com/109885044/196871536-bffe1e07-3523-4d86-a7e3-004323e86e20.png)

**Comment by soundsnow** [comment]
Game
Super Mario Land (World) (Rev 1).gb
Box art
Super Mario Land (World) (Rev 1).png

**Comment by philj56** [comment]
I don't currently have any plans to add box art, but I'm not 100% against it. If I ever do add it, it's going to be a long time from now, though.
