### ISSUE TITLE
Save folder location

### ISSUE THREAD

**Issue by CelestialAmber** [philj56/gbcc-android#2]
I tried to find where the save files are located, but I can't find where they are. Where are they located?

**Comment by philj56** [comment]
They're currently stored in the app's internal storage - you can't access them from a file manager or anything. You can import / export them from the app though, and in the most recent version I added a way to delete saves.

Looking back, I'm not sure that they *need* to be in the internal storage. It does have some benefits though:
  - Internal storage is always available, making e.g. cloud backup/restore reliable even on a new phone that hasn't had external storage set up.
  - Cloud backups have a pretty small maximum size (~25M), so putting saves somewhere people are unlikely to add loads of files reduces the likelihood of them failing. This is a pretty weak point though.
  - Save states (as opposed to normal in-game saves) will not work on different architectures, e.g. a save state made on a phone will not work on desktop. Having them be internal stops people from trying to do this, though there's no real reason they need to be in the same place as normal saves.

I think the first point is the only real argument that stops me from wanting to make the save directory reside on external storage along with the ROMs. There's presumably some way to handle it, but it'd probably be a bit messy. If many people find the existing ways to import/export/delete saves too cumbersome though, I'd be willing to give it a go.

**Comment by CelestialAmber** [comment]
Thanks for responding! Sorry for making an issue just to bring this up.

**Comment by philj56** [comment]
No problem, it was useful for me to reconsider why I made that choice in the first place!
