### ISSUE TITLE
Improvement: Rumble+SGB+GB supported GBC games

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#40]
7 Rumble+SGB+GB supported GBC games

Get Chuu Club - Minna no Konchuu Daizukan (Japan) (Rumble Version) (SGB Enhanced) (GB Compatible).gbc

Hole in One Golf (USA) (Rumble Version) (SGB Enhanced) (GB Compatible).gbc

Kawa no Nushi Tsuri 4 (Japan) (Rumble Version) (SGB Enhanced) (GB Compatible).gbc

Pokemon Pinball (Europe) (En,Fr,De,Es,It) (Rumble Version) (SGB Enhanced) (GB Compatible).gbc

Pokemon Pinball (Japan) (Rumble Version) (SGB Enhanced) (GB Compatible).gbc

Pokemon Pinball (USA, Australia) (Rumble Version) (SGB Enhanced) (GB Compatible).gbc

Test Drive Off-Road 3 (USA) (Rumble Version) (SGB Enhanced) (GB Compatible).gbc

**Comment by philj56** [comment]
I'm not sure what you're asking here - the rumble pak already works, and as I said in #17, I'm not currently planning on adding SNES features.
