### ISSUE TITLE
Camera image format

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#42]
Game Boy Camera
Emulate this accessory by either using the PC's webcam or sending a BMP, GIF, JPEG, PNG, or other image format to the game, as if it was coming from the camera itself.

**Comment by philj56** [comment]
This already mostly exists - on Android & Linux, the camera is working. On Windows / Mac, or if you don't give the Android app camera permissions, a placeholder image is used. I don't really have any desire to add an option to the Android version to change this image, as handling files on Android is a pain.
