### ISSUE TITLE
Question: accessories?

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#43]
Game Boy
Barcode Taisen Bardigun
Barcode Boy
4-Player Adapter
Pocket Sonar

Game Boy Color
Full Changer
Game Boy Color IR link
Mobile Network GB
Turbo File
Power Antenna & Bug Sensor
Singer Sewing Machine

**Comment by philj56** [comment]
Most of these are very niche things that I don't have current plans to emulate - not until the core emulation is much more accurate (e.g. allowing choice of emulated GameBoy model)
