### ISSUE TITLE
Bug: menu screen load .s10 file automatically

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#44]
All Default

To ensure that the test results are completely accident-free, please follow these
1. Force Stop GBCC
2. Delete save and states

Steps
1. Open GBCC
2. Open a Game
3. Open Menu Screen (Save State/ Load State/Autosave/Frameblend, Lin Cable/ Shader)
4. Circle (Android Navigation Bar - Home)
5. Back to GBCC
6. Close Menu Screen
7. It automatically loads the .s10 file

At that time I had been playing for 7 minutes, then I wanted to open the browser to check the walkthrough, I taped on the game screen to pause the game, go back to the home page, open Firefox, exit the browser back to GBCC, at this time the game screen changed, taped on the game screen, it became the state of my last exit from the game
So my time was wasted

**Comment by philj56** [comment]
Oops, good catch! `.s10` is the autosave state, which isn't being created if you close the app while the menu's open. I've fixed this [upstream](https://github.com/philj56/gbcc/commit/d0829f22f34cb8c0b99c99aef2aa0dc06dbe4dbf), it'll be updated here at some point and I'll close this issue then.

**Comment by philj56** [comment]
Alright, this should be fixed as part of 036dc078661fa1942ad69e59b0987341dfeb9b12.
