### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by y20k** [philj56/gbcc-android#5]
I have been playing with GBCC in the last couple of weeks. There is one feature that is either not present, or not easy to find: A reset button. I from time to time had the wish that I could restart the Game Boy so that I can load an in-game save.

**Comment by philj56** [comment]
Yeah, I could do with making the UI a bit clearer in general.

Quite a few games (e.g. Pokemon) have a way to reset built-in, by pressing A+B+START+SELECT at the same time (easiest to do by using two fingers to press B + Select, then sliding your fingers over A + Start or vice versa). Alternately, you could leave the game, disable autoresume in the settings, then open the game again (that's a bit kludgy though I guess).

I don't really want to add another button to the game screen, as I like it being as close to a physical gameboy as possible.

**Comment by y20k** [comment]
> I don't really want to add another button to the game screen, as I like it being as close to a physical gameboy as possible.

Okay. I can totally understand that. 

Another idea to implement this would be: The app could show a dialog when the user taps/swipes Back. 

```
Emulation paused.
Reset Game Boy | Quick Save and Exit
```

Just an idea. I recognize, that this behavior could annoy other users (than me). But I just wanted to mention it.

Cheers.

**Comment by y20k** [comment]
This is great. :partying_face:
