### ISSUE TITLE
Improvement: Slow/Fast and Custom Value

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#50]
Some games have characters or backgrounds that move quickly and require quick responses, even if multiple S/L are difficult to pass, so I think Slow is necessary
![fs](https://user-images.githubusercontent.com/109885044/200154194-683ec844-313b-40ce-a812-e097c7510786.png)

**Comment by soundsnow** [comment]
![image156](https://user-images.githubusercontent.com/109885044/200154343-a7ea0a7c-f3fc-4517-953a-b5c53e1239c4.png)

**Comment by philj56** [comment]
This is already possible from the menu screen:

![zopfli_2022-11-07T11:57:48,907882236+00:00](https://user-images.githubusercontent.com/13610623/200304931-69a958c0-f3ec-4bca-91fa-b453c24952a6.png)

You can also set a custom turbo limit in the app settings screen.
