### ISSUE TITLE
Improvement: Add shortcut

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#52]
Create a Shortcut for the games you want to play
This will save time opening the emulator and finding the game

Windows: Create a shortcut to Desktop for the game you're playing
Android: Add Content Shorcut to Launcher

Android Launcher
Touch & hold the widget to move it around the Home screen
Tetris (Japan) (En)
1 × 1
Cancel Add to Home screen

**Comment by philj56** [comment]
Yup, this is already on my old [to-do list](https://github.com/philj56/gbcc-android/issues/1)

**Comment by philj56** [comment]
Alright, I've added the ability to create shortcuts in 0a0312f344af53d98614fb181be7ecb59f7d8283:

![shortcuts](https://user-images.githubusercontent.com/13610623/202501785-5bb0a152-2096-4c3a-9a2c-bd6683e006ca.png)
