### ISSUE TITLE
Improvement: Snap-to-Grid Button Layout

### ISSUE THREAD

**Issue by ruvaldak** [philj56/gbcc-android#53]
Hello! For those of us with OCD, could it be possible to add an option for a Snap-to-Grid feature when editing the on-screen button Layout? That way things align properly? Thanks!

**Comment by ruvaldak** [comment]
Oh how exciting, thank you! I look forward to it's implementation.

**Comment by philj56** [comment]
Alright, I've added a grid-snapping option in 64bca5723f99e96466661563cb4674f9999deb41, which defaults to on. The size of the grid can't be changed currently (to avoid adding too many options), but it should be about the right tradeoff between ease of alignment and accuracy of placement. It's also symmetrical around the center of the screen.

![grid](https://user-images.githubusercontent.com/13610623/201400928-8a106140-8c70-40cd-b35a-fd202a23069a.png)

Thanks for the suggestion, it's much nicer having properly aligned custom layouts :)

**Comment by ruvaldak** [comment]
Amazing! Thank you so much <3 Might seem like such a small thing, but it makes me soo happy
