### ISSUE TITLE
Enhancement: Analog to play Air Hockey games

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#55]
I think D-Pad is not suitable for playing Air Hockey

[Arthur's Absolutely Fun Day! (GBC): Air Hockey Antics LOLFest!!!](https://youtu.be/bDay37xR9lU)

[Gta 4 Air Hockey minigame](https://youtu.be/IzxBFA9X5io)

**Comment by philj56** [comment]
Someone else already suggested this in #54.
