### ISSUE TITLE
Game Save file Paths and N64 Transfer Pak games

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#59]
To play Nintendo 64 Transfer Pak compatible games
you need at least 3 files

Pokemon Stadium (USA).z64 (the N64 rom).
Pokemon Stadium (USA).z64.sav (the GB save, change the .srm extension to .sav if needed, it won't work with .srm).
Pokemon Stadium (USA).z64.gb (the GB rom, if it's a GBC rom you'll need to rename .gbc to .gb).

So, I have a z64 and a gb/gbc
But, how to get a sav/srm?
I have to root my Android phone?

Add these

File Path
- Internal (1. data/data or data/user/0, 2. storage/emulated/0/Android/data or data/media/0/Android/data or sdcard/Android/data)
- External (1. Select Folder, 2. Same as Content)

Some regrets are that gbcc cannot import or replace Game Boy Camera photos with my own files
There're 2 Nintendo 64 Disk Drive (N64DD) games also support Game Boy Camera

[Transfer Pak compatible games](https://en.m.wikipedia.org/wiki/Nintendo_64_accessories#Transfer_Pak)

**Comment by philj56** [comment]
Saves are stored internally, but you can export them from the overflow menu on the main screen:

![export](https://user-images.githubusercontent.com/13610623/202895238-90cd985a-f9a8-4a59-bf2e-eef062d54eb5.png)

This'll give you a zip file containing all your `.sav`s. The main reason I did this was ease of programming, but it also means your saves should be automatically backed up to your google account.

I think at some point, I'll look into adding a second style of file browser, something like this:

![external](https://user-images.githubusercontent.com/13610623/202895933-941c1551-38f9-407e-88c2-01553269c7cf.png)

Games launched directly from external storage would store their `.sav` files next to them, as in other emulators.

For camera image import, that's quite a lot of work for a very niche feature, so I'll probably not do anything on that for quite a while at least.
