### ISSUE TITLE
Update! !atedpU

### ISSUE THREAD

**Issue by oong819** [philj56/gbcc-android#6]
i see a lot of commits this year but the google play app dont get a update long time

so will you update it?

thanks for this awesome emulator without any ads

**Comment by philj56** [comment]
Hi, yes I will update the Android app at some point, I just haven't done much work on it recently. I had wanted to get multiplayer in there at some point for the next update, but it's probably worth making a release sooner rather than later to fix some existing issues.

**Comment by philj56** [comment]
Ok, so I've finally started rolling out a new Android release, should be available within the next day or so. Sorry for the long break!

**Comment by philj56** [comment]
The latest update should now be available to everyone
