### ISSUE TITLE
good emulator

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#7]
yes! this is the best gbc emulator for android
camera, accelerometer
i added it to emulation general wiki
https://emulation.gametechwiki.com/index.php/Game_Boy/Game_Boy_Color_emulators#Emulators
https://emulation.gametechwiki.com/index.php/Special:MobileDiff/50634
https://emulation.gametechwiki.com/index.php/Special:MobileDiff/50636
other emulators don't support these features

**Comment by philj56** [comment]
Hey that's cool, thanks!
